# Generated by Django 4.2.3 on 2023-10-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesteader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='size',
            field=models.CharField(default='not set', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='first_yield_countdown_start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
