# Generated by Django 4.2.3 on 2023-10-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesteader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='size',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
