# Generated by Django 4.2.3 on 2023-11-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesteader', '0002_container_size_plant_first_yield_countdown_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
