# Generated by Django 4.2.3 on 2023-11-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesteader', '0003_plant_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
